name: CD Pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - manual
jobs:
  build:
    runs-on: 
      - self-hosted
      - label-1
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Docker-compose UP
        run: docker-compose up -d
